import { ESPLoader, Transport } from 'https://cdn.jsdelivr.net/npm/esptool-js@0.5.7/bundle.js';
// The adapter wraps the generated Emscripten module and exposes createLittleFS.
// Expected adapter: createLittleFS({blockSize, blockCount, ...}) -> {addFile(path,data), toImage()}.
import { createLittleFS } from './wasm/index.js';

const $=id=>document.getElementById(id); let loader,transport,partition,image;
const log=m=>{$('log').textContent+=m+'\n';$('log').scrollTop=1e9};
function hex(n){return '0x'+n.toString(16).toUpperCase()}
function parsePartitionTable(data){const out=[]; for(let p=0;p+32<=data.length;p+=32){const dv=new DataView(data.buffer,data.byteOffset+p,32);if(dv.getUint16(0,true)!==0x50aa) continue;const type=data[p+2],subtype=data[p+3],offset=dv.getUint32(4,true),size=dv.getUint32(8,true);let label='';for(let i=12;i<28&&data[p+i];i++)label+=String.fromCharCode(data[p+i]);out.push({type,subtype,offset,size,label});}return out}
async function readPartitions(){const table=await loader.readFlash(0x8000,0x1000);const parts=parsePartitionTable(table); let p=parts.find(x=>/littlefs/i.test(x.label));if(!p)p=parts.find(x=>x.type===1&&(x.subtype===0x82||x.subtype===0x83)); if(!p)throw Error('LittleFS partition not found. Rename/mark the data partition or edit selection logic.');partition=p;$('partition').textContent=JSON.stringify({label:p.label,offset:hex(p.offset),size:p.size,sizeMiB:(p.size/1048576).toFixed(2)},null,2);$('build').disabled=false;log('LittleFS partition found: '+p.label)}
$('connect').onclick=async()=>{try{if(!('serial'in navigator))throw Error('Web Serial requires Chrome/Edge.');const port=await navigator.serial.requestPort();transport=new Transport(port);loader=new ESPLoader({transport,baudrate:921600,terminal:{clean(){},writeLine:log,write:m=>log(String(m))}});await loader.main();$('status').textContent='Connected';log('Connected');await readPartitions()}catch(e){log('ERROR: '+e.message)}};
$('files').onchange=()=>{$('fileList').innerHTML='';[...$('files').files].forEach(f=>{$('fileList').insertAdjacentHTML('beforeend',`<li>${f.name} — ${(f.size/1048576).toFixed(2)} MiB</li>`)});};
$('build').onclick=async()=>{try{const fs=await createLittleFS({blockSize:4096,blockCount:partition.size/4096});for(const f of $('files').files){fs.addFile('/'+f.name,new Uint8Array(await f.arrayBuffer()))}image=fs.toImage();if(image.length>partition.size)throw Error('Image exceeds partition');$('image').textContent=`Image: ${image.length} bytes / ${partition.size} bytes`; $('write').disabled=false;log('Image built locally; existing LittleFS was never read.')}catch(e){log('BUILD ERROR: '+e.message)}};
$('write').onclick=async()=>{try{if(!image)throw Error('Build image first');log('Erasing LittleFS partition…');await loader.eraseRegion(partition.offset,partition.size);log('Writing '+image.length+' bytes…');const chunk=0x4000;for(let i=0;i<image.length;i+=chunk){const data=image.slice(i,i+chunk);await loader.writeFlash({fileArray:[{address:partition.offset+i,data}],flashSize:'keep',flashMode:'keep',flashFreq:'keep',eraseAll:false,compress:true,reportProgress:(idx,w,total)=>{$('progress').value=Math.round((i+w)/image.length*100)}})}$('progress').value=100;log('Done. Reset device manually or add reset after verifying your esptool-js version.')}catch(e){log('WRITE ERROR: '+e.message)}};
